config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :listings do
    resources :bookings, except: [:destroy]
  end
  
  resources :listings do
    resources :reviews, only: [:new, :create]
  end

  get '/listings/:id/profile', to: 'pages#caregiver_profile', as: 'caregiver_profile'
  get '/users/:id/listings', to: 'pages#by_user', as: 'user_listings'
  get '/about_us', to: 'pages#about_us', as: 'about_us'

  get '/users/:id', to: 'pages#profile', as: 'profile'
  post '/users/:id', to: 'bookings#update_status', as: 'status'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :listing

  STATUS = ["🟢", "Pending", "❌"]

  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :end_date_is_after_start_date
  validates :status, presence: true, inclusion: { in: STATUS }

  private

  def end_date_is_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "cannot be before the start date")
    end
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :global_search,
    against: %i[title service_description location fee],
    associated_against: {
      user: %i[first_name last_name description]
    },
    using: {
      tsearch: { prefix: true }
    }

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  validates :location, presence: true
  validates :title, presence: true, length: { maximum: 50 }
  validates :fee, presence: true
  validates :service_description, presence: true, length: { maximum: 500 }
  acts_as_taggable_on :tags

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  has_one_attached :photo
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :listing
  belongs_to :user

  validates :comment, length: { minimum: 20 }
  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  AGE_RANGE = %w[18-29 30-39 40-49 50-59 60-69 70+].freeze

  has_many :listings, dependent: :destroy
  has_many :bookings, dependent: :destroy

  validates :first_name, presence: true, length: { minimum: 2, maximum: 30 }
  validates :last_name, presence: true, length: { minimum: 2, maximum: 30 }
  validates :password, presence: true, confirmation: true
  validates :age_range, presence: true, inclusion: { in: AGE_RANGE, message: "%{value} is not a valid age range" } 
  has_one_attached :photo
  validates :photo, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  protected

  def configure_permitted_parameters
    added_attrs = [ :first_name, :last_name, :age_range, :languages, :phone_number, :description, :email, :password, :password_confirmation, :photo ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = policy_scope(Booking)
  end

  def new
    @listing = Listing.find(params[:listing_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @listing = Listing.find(params[:listing_id])
    @booking.listing = @listing
    @booking.user = current_user
    @booking.status = "Pending"
    authorize @booking
    if @booking.save
      redirect_to profile_path(current_user), notice: 'Booking was successfully created!'
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def update_status
    @booking = Booking.find(params[:booking_id])
    @booking.update(status: params[:status])
    authorize @booking
    redirect_to profile_path
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to listing_booking_path(@booking), notice: 'Booking was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to listing_bookings_path, notice: 'Booking was successfully deleted.'
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :notes)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :call_listing, only: [:show]

  def index
    @listings = policy_scope(Listing)
    @listings = Listing.global_search(params[:query]) if params[:query].present?
    @listings = Listing.tagged_with(params[:tag]) if params[:tag].present?
    @markers = @listings.geocoded.map do |listing|
      {
        lat: listing.latitude,
        lng: listing.longitude
      }
    end
  end

  def new
    @listing = Listing.new
    authorize @listing
  end

  def create
    @listing = Listing.new(listing_params)
    # @listing.tag_list.add(listing_params[:tag_list])
    @listing.user = current_user
    authorize @listing
    if @listing.save
      redirect_to listing_path(@listing), notice: 'Listing was successfully created!'
    else
      render :new
    end
  end

  def show
    @markers = [{
        lat: @listing.latitude,
        lng: @listing.longitude
    }]
    @review = Review.new
  end

  private

  def call_listing
    @listing = Listing.find(params[:id])
    authorize @listing
  end

  def listing_params
    params.require(:listing).permit(:fee, :service_description, :location, :title, :photo, :tag_list)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @listings = Listing.all
  end

  def about
  end

  def caregiver_profile
    @listing = Listing.find(params[:id])
    @user = @listing.user
  end

  def by_user
    @user = User.find(params[:id])
    @listings = @user.listings
  end

  def profile
    @my_bookings = current_user.bookings
    @my_listings = current_user.listings
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # def new
  #  @listing = Listing.find(params[:listing_id])
  #  @review = Review.new
  # end

  def create
    @listing = Listing.find(params[:listing_id])
    @review = Review.new(review_params)
    @review.listing = @listing
    @review.user = current_user
    authorize @review
    if @review.save
      redirect_to listing_path(@listing), notice: 'Review was successfully created!'
    else
      render 'listing_path'
    end
  end

  def show
    @review = Review.find(params[:listing_id])
  end

  private

  def review_params
    params.require(:review).permit(:nickname, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <div class="page-wrapper">
    <div class="row">
      <div class="column">
        <div class="left-column">
        </div>
      </div>
      <div class="column">
        <div class="right-column">
          <h1>Bookings</h1>
          <br>
          <% @bookings.each do |booking| %>
            <div class="booking-list-card">
              <%= link_to listing_path(booking.listing) do %>
                <p>Title: <%= booking.listing.title %></p>
                <p>Date: <%= booking.start_date %> - <%= booking.end_date %></p>
                <p>Status: <%= booking.status %></p>
              <% end %>
            <% end %>
          </div>
          <br>
          <br>
          <%= link_to 'Return to Listings', listings_path, class: "btn btn-secondary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container col-6">
  <div class="forms">
    <div class="card-booking">
      <h2>Booking</h2>
      <div class="card-booking-info">
        <div>
          <%= simple_form_for [@listing, @booking] do |f| %>
            <%= f.input :start_date, html5: true %>
            <%= f.input :end_date, html5: true %>
            <%= f.input :notes %>
            <%= f.submit class: 'book-action-btn' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <title>Share Care!</title>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="body-content">
      <%= yield %>
    </div>
    <%#= javascript_pack_tag 'map' %>
  </body>
</html>

app/views/listings/index.html.erb
<div class="main-container">
  <div class="listing-layout">
    <h2 id="title">Spend time with...</h2>
    <%= render 'shared/card-listings-l' %>
  </div>
  <div><%= render 'shared/map' %></div>
</div>

app/views/listings/new.html.erb
<div class="container col-6">
  <div class="card-booking">
    <h2>How Can You Share?</h2>
    <div class="card-booking-info">
      <div>
        <%= simple_form_for [@listing] do |f| %>
          <%= f.input :title %>
          <%= f.input :service_description %>
          <%= f.input :tag_list, placeholder: "Separate tags with comma..." %>
          <%= f.input :location %>
          <%= f.input :fee %>
          <%= f.input :photo, as: :file %>
          <%= f.submit class: 'book-action-btn' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/listings/show.html.erb
<div class="container">
  <div class="listing-show-title">
    <h2><%= @listing.title.capitalize %></h2>
  </div>
  <div class="listing-photo">
    <% if @listing.photo.attached? %>
      <%= cl_image_tag @listing.photo.key, class: "listing-photo" %>
    <% else %>
      <%= image_tag "https://images.pexels.com/photos/3662630/pexels-photo-3662630.jpeg?cs=srgb&dl=pexels-cottonbro-3662630.jpg&fm=jpg", class: "listing-photo" %>
    <% end %>
  </div>
  <div class="listing-content">
    <div class="profile-booking">
      <div class="profile-photo-full-name">
        <div class= "owner-photo">
          <%= cl_image_tag @listing.user.photo.key, class: "owner-photo" %>
        </div>
        <div class="full-name-link">
          <p>
            <%= @listing.user.first_name %>
            <%= @listing.user.last_name %>
          </p>
        </div>
        <%= link_to "", caregiver_profile_path(@listing), class: "profile-photo-full-name-link" %>
      </div>
      <div>
        <%= link_to "Book an activity", new_listing_booking_path(@listing), class: "book-action-btn"%>
      </div>
    </div>
    <div class="listing-content-right">
      <div class="listing-show-items">
        <div class="listing-show-item">
          <div class="listing-show-item-icon">
            <h2><strong><i class="fas fa-hands-helping"></i></strong></h2>
          </div>
          <div class="listing-show-item-sheading">
            <h2>How the kids will spend time with <%= @listing.user.first_name %></h2>
            <div class="listing-show-item-content">
              <p><%= @listing.service_description %></p>
            </div>
          </div>
        </div>
        <div class="listing-show-item">
          <div class="listing-show-item-icon">
            <h2><strong><i class="fas fa-hand-holding-heart"></i></strong></h2>
          </div>
          <div class="listing-show-item-sheading">
            <h2>Fee</h2>
            <div class="listing-show-item-content">
              <p><%= @listing.fee %> per hour</p>
            </div>
          </div>
        </div>
        <div class="listing-show-item">
          <div class="listing-show-item-icon">
            <h2><strong><i class="fas fa-hand-sparkles"></i></strong></h2>
          </div>
          <div class="listing-show-item-sheading">
            <h2>Skills</h2>
            <div class="listing-show-item-content">
              <%= render 'shared/tag-list' %>
            </div>
          </div>
        </div>
        <div class="listing-show-item">
          <div class="listing-show-item-icon">
            <h2><i class="fas fa-map-marked-alt"></i></h2>
          </div>
          <div class="listing-show-item-sheading">
            <h2>Location</h2>
            <div class="listing-show-item-content">
              <p><%= @listing.location %></p>
            </div>
          </div>
        </div>
        <div id="map"
      style="width: 100%; height: 400px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
      <div class="listing-show-items">
        <div class="listing-show-item">
          <% unless current_user == @listing.user %>
            <div class="listing-show-item-icon">
              <h2><i class="fas fa-thumbs-up"></i></h2>
            </div>
            <div class="listing-show-item-sheading">
              <h2>Review</h2>
              <div class="listing-show-item-content">
                <p>How was the activity? Write a review.</p>
                <%= render 'shared/review-form' %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="listing-show-item">
          <div class="listing-show-item-icon">
            <h2><i class="fas fa-comments"></i> </h2>
          </div>
          <div class="listing-show-item-sheading">
            <h2>Recent Reviews</h2>
            <div class="listing-show-item-content">
              <% @listing.reviews.each do |review| %>
                <div class="review-card p-3 mt-2">
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="user d-flex flex-row align-items-center">
                      <span><small class="font-weight-bold text-primary"><%= review.user.first_name %>: </small><br>
                        <small class="font-weight-bold"><%= review.comment %></small></span>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/by_user.html.erb
<div class="main-container">
  <div class="listing-layout">
    <h2>All listings by <%= @user.first_name %></h2>
    <%= render 'shared/card-listings-l' %>
  </div>
  <div><%= render 'shared/map' %></div>
</div>

app/views/pages/caregiver_profile.html.erb
<div class="container 800-container">
  <div class="profile-content">
    <div class="profile-booking">
      <div class= "profile-photo-full-name">
        <div class= "owner-photo">
          <%= cl_image_tag @user.photo.key, class: "owner-photo", alt: "Profile Picture" %>
        </div>
        <div class="full-name-link">
          <p>
            <%= @user.first_name %>'s listings
          </p>
        </div>
        <%= link_to "", user_listings_path(@user), class: "profile-photo-full-name-link" %>
      </div>
    </div>
    <div class="listing-content-right">
      <h2>More about the caregiver...</h2>
      <br>
      <br>
      <%= render '/shared/caregiver-profile' %>
      <div class="return-btn">
        <%= link_to 'Return to the listing', listing_path(@listing), class: "book-action-btn" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="container 800-container">
  <div class="profile-content">
    <div class="profile-booking">
      <div class="profile-photo-full-name">
        <div class= "owner-photo">
          <%= cl_image_tag current_user.photo.key, class: "owner-photo", alt: "Profile Picture" %>
        </div>
        <div class="full-name-link">
          <p>
            <% if current_user.listings %>
              <%= link_to 'My listings', user_listings_path(current_user) %>
            <% end %>
          </p>
        </div>
        <%= link_to "", user_listings_path(current_user), class: "profile-photo-full-name-link" %>
      </div>
    </div>
    <div class="listing-content-right">
      <h2>My profile & Bookings</h2>
      <br>
      <br>
      <%= render '/shared/user-details' %>
      <div class="booking-section">
        <div class="listing-show-items">
          <div class="listing-show-item">
            <div class="listing-show-item-icon">
              <h2><strong><i class="fas fa-hands-helping"></i></strong></h2>
            </div>
            <div class="listing-show-item-sheading">
              <h2>Reserved activities </h2>
              <div class="listing-show-item-content">
              </div>
            </div>
          </div>
        </div>
        <ul class="nav nav-tabs bootstrap-tabs" id="myTab" role="tablist">
          <li class="nav-item" role="presentation">
            <a class="nav-link active" id="home-tab" data-bs-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Hosting</a>
          </li>
          <li class="nav-item" role="presentation">
            <a class="nav-link" id="profile-tab" data-bs-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Visting</a>
          </li>
        </ul>
        <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab"><%= render '/shared/received-booking-card' %></div>
          <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab"><%= render '/shared/my-booking-card' %></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="window" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://images.pexels.com/photos/3094230/pexels-photo-3094230.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260);">
  <div class="container">
    <div class="search-bar-home">
      <%= form_tag listings_path, method: :get do %>
        <div class="d-flex input-group rounded">
          <%= text_field_tag :query,
            params[:query], 
            class: "form-control search-bar",
            placeholder: "Find a caregiver"
          %>
          <%= submit_tag "Search", class: "btn btn-secondary" %>
        </div>
        <% end %>
    </div>
    <h1>Share Care!</h1>
    <p>Enrich your child's life with our highly skilled caregivers.</p>
  </div>
</div>

app/views/shared/_caregiver-profile.html.erb
<div class="listing-show-items">
  <div class="listing-show-item">
    <div class="listing-show-item-icon">
      <h2><strong><i class="fas fa-user-circle"></i></strong></h2>
    </div>
    <div class="listing-show-item-sheading">
      <h2><%= @user.first_name %> <%= @user.last_name %></h2>
      <% if @user.phone_number.nil? %>
        <p>Phone number: Verified <i class="far fa-check-circle"></i></p>
      <% end %>
      <% if @user.listings %>
        <p><i class="fas fa-location-arrow"></i>
          <%= @user.listings.first.location %>
        <% end %>
      </p>
      <div class="listing-show-item-content">
      </div>
    </div>
  </div>
</div>
<div class="listing-show-items">
  <div class="listing-show-item">
    <div class="listing-show-item-icon">
      <h2><strong><i class="fas fa-signature"></i></i></strong></h2>
  </div>
  <div class="listing-show-item-sheading">
    <h2>About</h2>
    <div class="listing-show-item-content">
      <p><%= @user.description %></p>
    </div>
  </div>
</div>
<div class="listing-show-items">
  <div class="listing-show-item">
    <div class="listing-show-item-icon">
      <h2><strong><i class="fas fa-hand-sparkles"></i></strong></h2>
    </div>
    <div class="listing-show-item-sheading">
      <h2>Skills</h2>
      <div class="listing-show-item-content">
        <% if @user.listings.empty? %>
          <p>You have no skill tags.</p>
          <p><%= link_to 'Create a new listing to add new tags', new_listing_path %></p>
        <% else %>
          <% @user.listings.each do |listing| %>
            <% listing.tag_list.each do |tag| %>
              <%= link_to listings_path(tag: tag), class: "btn btn-secondary btn-sm mx-1" do %>
                <%= tag %>
              <% end %>
            <% end %>
          <% end %>
          <br>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_listing-banner.html.erb
<div class="listing-banner">
  <%= image_tag "https://source.unsplash.com/-_QpJv4J_AA", class: "listing-photo" %>
  <div class="owner-info">
    <%= image_tag "https://images.unsplash.com/photo-1534286802268-99ddb388ed4c?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=934&q=80", class: "owner-photo" %>
    <%= link_to caregiver_profile_path(@listing), class: "btn btn-info contact-btn" do %>
      <%= @listing.user.first_name %> <span><%= @listing.user.last_name %>
    <% end %>
  </div>
</div>

app/views/shared/_map.html.erb
<div id="map"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/shared/_my-booking-card.html.erb
  <% if @my_bookings.empty? %>
  <p>No bookings found.</p>
  <p><%= link_to 'Find a caregiver', listings_path %></p>
<% else %>
  <% @my_bookings.each do |booking| %>
    <div class="accordion" id="accordionExample">
      <div class="card">
        <div class="card-header" id=<%="heading#{booking.id.to_s}"%>>
          <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target=<%="#collapse#{booking.id.to_s}"%> aria-expanded="true" aria-controls=<%="collapse#{booking.id.to_s}"%>>
            <div><%= link_to listing_path(booking.listing.id) do %>
                <strong><%= booking.listing.title.capitalize %></strong>
              <% end %>
            </div>
            <div class="booking-table">
              <div><%= booking.start_date.to_s(:short) %> ~ <%= booking.end_date.to_s(:short) %></div>
              <div><%= booking.status %></div>
            </div>
          </button>
        </div>
        <div id=<%="collapse#{booking.id.to_s}"%> class="collapse" aria-labelledby=<%="heading#{booking.id.to_s}"%> data-parent="#accordionExample">
          <div class="card-body">
            <p>📝 <%= booking.notes %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path do %>
    <%= image_tag "share-care-logo.png", alt: "alttext", class: "navbar-logo" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "All Listings", listings_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to profile_path(current_user), class: "dropdown-item" do %>
              👋 Welcome <%= current_user.first_name %>
            <% end %>
            <%= link_to "Add a listing", new_listing_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_profile-booking.html.erb
<div class="profile-booking">
  <div class="profile-photo-full-name">
    <div class= "owner-photo">
      <%= cl_image_tag @listing.user.photo.key, class: "owner-photo" %>
    </div>
    <div class="full-name-link">
      <p>
        <%= @listing.user.first_name %>
        <%= @listing.user.last_name %>
      </p>
    </div>
    <%= link_to "", caregiver_profile_path(@listing), class: "profile-photo-full-name-link" %>
  </div>
  <div>
    <%= link_to "Book an activity", new_listing_booking_path(@listing), class: "book-action-btn"%>
  </div>
</div>

app/views/shared/_received-booking-card.html.erb
<% @my_listings.each do |listing| %>
  <% if listing.bookings.nil? %>
    <p>You have no bookings.</p>
  <% else %>
    <% listing.bookings.each do |booking| %>
      <div class="accordion" id="accordionExample">
        <div class="card">
          <div class="card-header" id=<%="heading#{booking.id.to_s}"%>>
            <button class="accordion-link btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target=<%="#collapse#{booking.id.to_s}"%> aria-expanded="true" aria-controls=<%="collapse#{booking.id.to_s}"%>>
              <div class="booking-btn-title"><%= link_to listing_path(listing) do %>
                  <strong><%= booking.listing.title.capitalize %></strong>
                <% end %>
              </div>
              <div class="booking-table">
                <div><%= booking.start_date.to_s(:short) %> ~ <%= booking.end_date.to_s(:short) %></div>
                <% if booking.status == "Pending" %>
                  <div><%= booking.status %></div>
                  <div>
                    <%= simple_form_for status_path do |f| %>
                      <%= f.hidden_field :status, name:"booking_id", value: booking.id, class: "status" %>
                      <%= f.button :submit, name: "status", value: "🟢" %>
                      <%= f.button :submit, name: "status", value: "❌" %>
                    <% end %>
                  </div>
                <% else %>
                  <div><%= booking.status %></div>
                <% end %>
              </div>
            </div>
          </button>
        </div>
        <div class="card-body">
          <div id=<%="collapse#{booking.id.to_s}"%> class="collapse" aria-labelledby=<%="heading#{booking.id.to_s}"%> data-parent="#accordionExample">
            <div class="booking-notes">
              <p>📝 <%= booking.notes %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_tag-list.html.erb
<% @listing.tag_list.each do |tag| %>
  <%= link_to listings_path(tag: tag), class: "btn btn-secondary btn-sm mx-1" do %>
    <%= tag %>
  <% end %>
<% end %>

app/views/shared/_user-profile-photo.html.erb
<div class="user-photo">
  <%= cl_image_tag current_user.photo.key %>
  <% if current_user.listings %>
    <%= link_to 'My listings', user_listings_path(current_user), class: "btn btn-secondary" %>
  <% end %>
  <% if current_user.phone_number %>
    <p>Phone number: Verified <i class="far fa-check-circle"></i></p>
  <% end %>
</div>